---
nginx_checksum: "23b8ff4a76817090678f91b0efbfcef59a93492f6612dc8370c44c1f1ce1b626"
nginx_extra_configure_flags: "--with-http_gzip_static_module"
nginx_version: "1.4.7"

passenger_version: "4.0.40"

nginx_location: "/opt/nginx-{{ nginx_version }}-passenger-{{ passenger_version }}"
